name: Test @novu/notification-center-vue
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/notification-center-vue/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.0

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build,test
          projects: '@novu/notification-center-vue'
          nxCloud: true
